export const MIXPANEL_EVENTS = {
    HERO_CTA_CLICK: 'HERO_CTA_CLICK',
    FEATURE_CLICK: 'FEATURE_CLICK',
    TOOL_CLICK: 'TOOL_CLICK',
    TOOL_SUCCESS: 'TOOL_SUCCESS',
    TOOL_ERROR: 'TOOL_ERROR',
    TOOL_START: 'TOOL_START',
    TOOL_COMPLETE: 'TOOL_COMPLETE',
    FILE_SELECTED: 'FILE_SELECTED',
    FILE_PREVIEWED: 'FILE_PREVIEWED',
    FILE_DOWNLOADED: 'FILE_DOWNLOADED',
    
}